
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /

spring:
  application:
    name: turbine

server:
  port: 8989

turbine:
  app-config: RIBBON-CONSUMER,hello-service
  aggregato:
    clusterConfig: default
  clusterNameExpression: new String("default")

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


