eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: hello-service
server:
  port: 8081


management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /