spring:
  application:
    name: ribbon-consumer
server:
  port: 9000
eureka:
  client:
    register-with-eureka: false #客户端不注册到eureka，只是进行服务的调用
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /