spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mightyzhu/springcloudexercise/
          search-paths: config-repo
          username: mighty_zhu@hotmail.com
          password: zwb1988520
server:
  port: 8070
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

